# Generated by Django 4.1.5 on 2023-01-15 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created Timestamp",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Updated Timestamp",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="is active", verbose_name="Is active"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the rule",
                        max_length=300,
                        verbose_name="Rule Name",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rules",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DailyTracker",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created Timestamp",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Updated Timestamp",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="is active", verbose_name="Is active"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("status", models.BooleanField(verbose_name="Completed")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Date"
                    ),
                ),
                (
                    "rule_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="health.rule",
                        verbose_name="rule id",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DailyTrackers",
                "ordering": ["-id"],
                "unique_together": {("date", "rule_id")},
            },
        ),
    ]
