# Generated by Django 4.1.5 on 2023-01-25 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FitbitDailyActivity",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Created Timestamp",
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Updated Timestamp",
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="is active", verbose_name="Is active"
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Date"
                    ),
                ),
                (
                    "calories_burned",
                    models.IntegerField(verbose_name="Calories Burned"),
                ),
                ("steps", models.IntegerField(verbose_name="Steps")),
                ("distance", models.IntegerField(verbose_name="Distance")),
                ("floors", models.IntegerField(verbose_name="Floors")),
                (
                    "minutes_sedentary",
                    models.IntegerField(verbose_name="Minutes sedentary"),
                ),
                (
                    "minutes_lightly_active",
                    models.IntegerField(verbose_name="Minutes lightly active"),
                ),
                (
                    "minutes_fairly_active",
                    models.IntegerField(verbose_name="Minutes fairly active"),
                ),
                (
                    "minutes_very_active",
                    models.IntegerField(verbose_name="Minutes very active"),
                ),
                (
                    "activity_calories",
                    models.IntegerField(verbose_name="Activity Calories"),
                ),
            ],
            options={
                "verbose_name_plural": "FitbitDailyActivity",
                "ordering": ["-id"],
            },
        ),
    ]
