# Generated by Django 4.1.5 on 2023-01-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_fitbitdailyactivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fitbitdailyactivity",
            name="distance",
            field=models.FloatField(verbose_name="Distance"),
        ),
    ]
