# Generated by Django 4.1.5 on 2023-01-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Task Name"),
        ),
    ]
